// Países del registro (mismo orden y prefijos que public/registration.html).
// `value` es el prefijo del DNI compuesto: <value>-<número> (V-12345678).

export interface Country {
  value: string;
  label: string;
  flag: string;
  /** Lo que se ve dentro del campo DNI ("V-", "COL-"...). */
  prefix: string;
}

export const COUNTRIES: Country[] = [
  { value: "V", label: "Venezuela", flag: '🇻🇪', prefix: "V-" },
  { value: "DEU", label: "Alemania", flag: '🇩🇪', prefix: "DEU-" },
  { value: "SAU", label: "Arabia Saudita", flag: '🇸🇦', prefix: "SAU-" },
  { value: "ARG", label: "Argentina", flag: '🇦🇷', prefix: "ARG-" },
  { value: "ABW", label: "Aruba", flag: '🇦🇼', prefix: "ABW-" },
  { value: "AUS", label: "Australia", flag: '🇦🇺', prefix: "AUS-" },
  { value: "AUT", label: "Austria", flag: '🇦🇹', prefix: "AUT-" },
  { value: "BEL", label: "Bélgica", flag: '🇧🇪', prefix: "BEL-" },
  { value: "BLZ", label: "Belice", flag: '🇧🇿', prefix: "BLZ-" },
  { value: "BOL", label: "Bolivia", flag: '🇧🇴', prefix: "BOL-" },
  { value: "BRA", label: "Brasil", flag: '🇧🇷', prefix: "BRA-" },
  { value: "CAN", label: "Canadá", flag: '🇨🇦', prefix: "CAN-" },
  { value: "CHL", label: "Chile", flag: '🇨🇱', prefix: "CHL-" },
  { value: "CHN", label: "China", flag: '🇨🇳', prefix: "CHN-" },
  { value: "COL", label: "Colombia", flag: '🇨🇴', prefix: "COL-" },
  { value: "KOR", label: "Corea del Sur", flag: '🇰🇷', prefix: "KOR-" },
  { value: "CRI", label: "Costa Rica", flag: '🇨🇷', prefix: "CRI-" },
  { value: "CUB", label: "Cuba", flag: '🇨🇺', prefix: "CUB-" },
  { value: "CUW", label: "Curazao", flag: '🇨🇼', prefix: "CUW-" },
  { value: "DNK", label: "Dinamarca", flag: '🇩🇰', prefix: "DNK-" },
  { value: "ECU", label: "Ecuador", flag: '🇪🇨', prefix: "ECU-" },
  { value: "EGY", label: "Egipto", flag: '🇪🇬', prefix: "EGY-" },
  { value: "SLV", label: "El Salvador", flag: '🇸🇻', prefix: "SLV-" },
  { value: "ARE", label: "Emiratos Árabes Unidos", flag: '🇦🇪', prefix: "ARE-" },
  { value: "ESP", label: "España", flag: '🇪🇸', prefix: "ESP-" },
  { value: "USA", label: "Estados Unidos", flag: '🇺🇸', prefix: "USA-" },
  { value: "PHL", label: "Filipinas", flag: '🇵🇭', prefix: "PHL-" },
  { value: "FIN", label: "Finlandia", flag: '🇫🇮', prefix: "FIN-" },
  { value: "FRA", label: "Francia", flag: '🇫🇷', prefix: "FRA-" },
  { value: "GRC", label: "Grecia", flag: '🇬🇷', prefix: "GRC-" },
  { value: "GTM", label: "Guatemala", flag: '🇬🇹', prefix: "GTM-" },
  { value: "GNQ", label: "Guinea Ecuatorial", flag: '🇬🇶', prefix: "GNQ-" },
  { value: "GUY", label: "Guyana", flag: '🇬🇾', prefix: "GUY-" },
  { value: "HTI", label: "Haití", flag: '🇭🇹', prefix: "HTI-" },
  { value: "HND", label: "Honduras", flag: '🇭🇳', prefix: "HND-" },
  { value: "IND", label: "India", flag: '🇮🇳', prefix: "IND-" },
  { value: "IRL", label: "Irlanda", flag: '🇮🇪', prefix: "IRL-" },
  { value: "ISR", label: "Israel", flag: '🇮🇱', prefix: "ISR-" },
  { value: "ITA", label: "Italia", flag: '🇮🇹', prefix: "ITA-" },
  { value: "JAM", label: "Jamaica", flag: '🇯🇲', prefix: "JAM-" },
  { value: "JPN", label: "Japón", flag: '🇯🇵', prefix: "JPN-" },
  { value: "LBN", label: "Líbano", flag: '🇱🇧', prefix: "LBN-" },
  { value: "MAR", label: "Marruecos", flag: '🇲🇦', prefix: "MAR-" },
  { value: "MEX", label: "México", flag: '🇲🇽', prefix: "MEX-" },
  { value: "NIC", label: "Nicaragua", flag: '🇳🇮', prefix: "NIC-" },
  { value: "NGA", label: "Nigeria", flag: '🇳🇬', prefix: "NGA-" },
  { value: "NOR", label: "Noruega", flag: '🇳🇴', prefix: "NOR-" },
  { value: "NZL", label: "Nueva Zelanda", flag: '🇳🇿', prefix: "NZL-" },
  { value: "NLD", label: "Países Bajos", flag: '🇳🇱', prefix: "NLD-" },
  { value: "PAN", label: "Panamá", flag: '🇵🇦', prefix: "PAN-" },
  { value: "PRY", label: "Paraguay", flag: '🇵🇾', prefix: "PRY-" },
  { value: "PER", label: "Perú", flag: '🇵🇪', prefix: "PER-" },
  { value: "POL", label: "Polonia", flag: '🇵🇱', prefix: "POL-" },
  { value: "PRT", label: "Portugal", flag: '🇵🇹', prefix: "PRT-" },
  { value: "PRI", label: "Puerto Rico", flag: '🇵🇷', prefix: "PRI-" },
  { value: "GBR", label: "Reino Unido", flag: '🇬🇧', prefix: "GBR-" },
  { value: "DOM", label: "Rep. Dominicana", flag: '🇩🇴', prefix: "DOM-" },
  { value: "ROU", label: "Rumania", flag: '🇷🇴', prefix: "ROU-" },
  { value: "RUS", label: "Rusia", flag: '🇷🇺', prefix: "RUS-" },
  { value: "SYR", label: "Siria", flag: '🇸🇾', prefix: "SYR-" },
  { value: "ZAF", label: "Sudáfrica", flag: '🇿🇦', prefix: "ZAF-" },
  { value: "SWE", label: "Suecia", flag: '🇸🇪', prefix: "SWE-" },
  { value: "CHE", label: "Suiza", flag: '🇨🇭', prefix: "CHE-" },
  { value: "SUR", label: "Surinam", flag: '🇸🇷', prefix: "SUR-" },
  { value: "TTO", label: "Trinidad y Tobago", flag: '🇹🇹', prefix: "TTO-" },
  { value: "TUR", label: "Turquía", flag: '🇹🇷', prefix: "TUR-" },
  { value: "UKR", label: "Ucrania", flag: '🇺🇦', prefix: "UKR-" },
  { value: "URY", label: "Uruguay", flag: '🇺🇾', prefix: "URY-" },
];
