// Recetas de la página de dieta (las mismas de public/diet.html).

export interface Recipe {
  id: number;
  name: string;
  emoji: string;
  /** Categorías separadas por espacios ('keto singluten'). */
  cat: string;
  level: 'principiante' | 'intermedio' | 'avanzado';
  time: number;
  kcal: number;
  servings: number;
  prot: number;
  carb: number;
  fat: number;
  desc: string;
  ingredients: string[];
  steps: string[];
}

/** Tarjeta del catálogo: su texto no siempre coincide con el de la receta. */
export interface RecipeCard {
  id: number;
  cat: string;
  level: Recipe['level'];
  levelLabel: string;
  accent: string;
  icon: string;
  title: string;
  desc: string;
  time: string;
  kcal: string;
  servings: string;
}

export const RECIPES: Recipe[] = [
  {
    id: 1,
    name: 'Buddha Bowl de Quinoa',
    emoji: '🥗',
    cat: 'vegano',
    level: 'principiante',
    time: 25,
    kcal: 420,
    servings: 2,
    prot: 18,
    carb: 52,
    fat: 14,
    desc: 'Bowl nutritivo con quinoa, garbanzos crujientes, aguacate, espinacas y aderezo tahini. Rico en proteína vegetal y fibra.',
    ingredients: [
      '200g quinoa',
      '1 lata garbanzos',
      '1 aguacate',
      '100g espinacas',
      'Cherry tomatoes',
      '3 cdas tahini',
      '1 limón',
      'Aceite de oliva',
      'Sal, comino, pimentón',
    ],
    steps: [
      'Cocer quinoa en agua con sal durante 15 min hasta que absorba el líquido.',
      'Escurrir garbanzos, condimentar con aceite, comino y pimentón. Asar en horno 200°C por 20 min.',
      'Preparar aderezo: tahini + zumo de limón + agua fría + sal. Remover hasta obtener salsa.',
      'Disponer quinoa en base. Agregar espinacas, garbanzos, aguacate y tomates. Verter aderezo al gusto.',
    ],
  },
  {
    id: 2,
    name: 'Curry de Garbanzos',
    emoji: '🍛',
    cat: 'vegano',
    level: 'intermedio',
    time: 35,
    kcal: 380,
    servings: 4,
    prot: 14,
    carb: 48,
    fat: 16,
    desc: 'Curry cremoso con leche de coco, garbanzos, tomate, jengibre y especias aromáticas. Servir con arroz basmati.',
    ingredients: [
      '2 latas garbanzos',
      '400ml leche de coco',
      '400g tomate triturado',
      '1 cebolla',
      '3 dientes ajo',
      '2cm jengibre fresco',
      'Curry en polvo',
      'Cúrcuma',
      'Aceite de coco',
    ],
    steps: [
      'Sofreír cebolla picada en aceite de coco hasta dorar. Añadir ajo y jengibre rallado.',
      'Agregar especias (curry, cúrcuma, garam masala) y tostar 1 min revolviendo.',
      'Incorporar tomate triturado. Cocinar 5 min a fuego medio.',
      'Añadir garbanzos escurridos y leche de coco. Cocinar 15 min hasta espesar. Salpimentar.',
    ],
  },
  {
    id: 3,
    name: 'Tacos de Jackfruit BBQ',
    emoji: '🌮',
    cat: 'vegano',
    level: 'intermedio',
    time: 40,
    kcal: 310,
    servings: 3,
    prot: 9,
    carb: 52,
    fat: 8,
    desc: 'Jackfruit desmenuzado con salsa BBQ ahumada, col morada encurtida y crema de cilantro.',
    ingredients: [
      '2 latas jackfruit',
      'Salsa BBQ vegana',
      'Col morada',
      'Vinagre de manzana',
      'Cilantro',
      'Crema de coco',
      'Limón',
      'Tortillas maíz',
      'Ajo en polvo',
    ],
    steps: [
      'Escurrir jackfruit, desmenuzar con tenedor y marinar en BBQ + ajo 15 min.',
      'Encurtir col morada fina con vinagre, sal y azúcar. Reservar.',
      'Saltear jackfruit en sartén caliente hasta caramelizar. Añadir más BBQ al gusto.',
      'Preparar crema de cilantro: coco + cilantro + limón en licuadora. Armar tacos.',
    ],
  },
  {
    id: 4,
    name: 'Smoothie Verde Energizante',
    emoji: '🥤',
    cat: 'vegano',
    level: 'principiante',
    time: 5,
    kcal: 220,
    servings: 1,
    prot: 6,
    carb: 34,
    fat: 7,
    desc: 'Licuado de espinaca, mango, jengibre, leche de almendras y semillas de chía.',
    ingredients: [
      '60g espinaca fresca',
      '150g mango congelado',
      '1cm jengibre',
      '300ml leche almendras',
      '1 cda semillas chía',
      'Zumo 1/2 limón',
      'Hielo al gusto',
    ],
    steps: [
      'Agregar todos los ingredientes a la licuadora en este orden: líquidos, espinaca, frutas.',
      'Licuar a velocidad alta 60 segundos hasta obtener textura completamente lisa.',
      'Verter sobre vaso con hielo. Decorar con semillas de chía. Servir inmediatamente.',
    ],
  },
  {
    id: 5,
    name: 'Salmón con Aguacate',
    emoji: '🐟',
    cat: 'keto',
    level: 'principiante',
    time: 20,
    kcal: 550,
    servings: 2,
    prot: 42,
    carb: 4,
    fat: 40,
    desc: 'Filete de salmón a la plancha con salsa de aguacate y limón, acompañado de espárragos salteados en mantequilla.',
    ingredients: [
      '2 filetes salmón 180g c/u',
      '1 aguacate maduro',
      '12 espárragos',
      '30g mantequilla',
      '1 limón',
      'Ajo',
      'Sal, pimienta',
      'Eneldo fresco',
    ],
    steps: [
      'Sazonar salmón con sal, pimienta y eneldo. Calentar sartén con aceite a fuego alto.',
      'Cocinar salmón 3-4 min por lado hasta piel crujiente y centro sonrosado.',
      'Saltear espárragos en mantequilla con ajo 3 min hasta tiernos pero crujientes.',
      'Preparar guacamole rápido: aguacate + limón + sal. Servir junto al salmón.',
    ],
  },
  {
    id: 6,
    name: 'Huevos con Bacon Keto',
    emoji: '🥚',
    cat: 'keto',
    level: 'principiante',
    time: 15,
    kcal: 420,
    servings: 1,
    prot: 28,
    carb: 2,
    fat: 33,
    desc: 'Huevos revueltos cremosos con bacon crujiente, queso parmesano y cebollín.',
    ingredients: [
      '3 huevos grandes',
      '4 lonchas bacon',
      '25g parmesano rallado',
      '2 cdas mantequilla',
      'Cebollín',
      'Sal, pimienta negra',
      'Crema 1 cda (opcional)',
    ],
    steps: [
      'Cocinar bacon en sartén fría, subir fuego gradualmente hasta crujiente. Retirar y reservar.',
      'Batir huevos con crema, sal y pimienta. En la misma sartén con mantequilla a fuego bajo.',
      'Remover constantemente con espátula dibujando ochos. Retirar del fuego mientras aún brillantes.',
      'Emplatar, rallar parmesano encima, agregar bacon troceado y cebollín picado.',
    ],
  },
  {
    id: 7,
    name: 'Pollo al Limón Keto',
    emoji: '🍗',
    cat: 'keto',
    level: 'intermedio',
    time: 30,
    kcal: 480,
    servings: 2,
    prot: 44,
    carb: 5,
    fat: 30,
    desc: 'Muslos de pollo a la sartén con salsa de mantequilla, limón y ajo, acompañados de coliflor gratinada con queso.',
    ingredients: [
      '4 muslos pollo',
      '200g coliflor',
      '60g queso gruyère',
      '40g mantequilla',
      '3 dientes ajo',
      '1 limón',
      'Tomillo',
      'Caldo de pollo 100ml',
    ],
    steps: [
      'Dorar muslos con piel en sartén caliente 5 min por lado. Salpimentar generosamente.',
      'Agregar ajo laminado, tomillo y desgrasar con caldo. Tapar y cocinar 15 min.',
      'Coliflor en florets, blanquear 3 min, escurrir y gratinar con queso 10 min a 200°C.',
      'Añadir mantequilla y limón a la sartén. Glasear el pollo 2 min. Servir con coliflor.',
    ],
  },
  {
    id: 8,
    name: 'Pechuga con Arroz',
    emoji: '🏋️',
    cat: 'proteina',
    level: 'principiante',
    time: 20,
    kcal: 520,
    servings: 1,
    prot: 52,
    carb: 48,
    fat: 9,
    desc: 'Pechuga de pollo a la plancha con condimento de hierbas, arroz integral y verduras al vapor.',
    ingredients: [
      '200g pechuga pollo',
      '100g arroz integral',
      'Brócoli 100g',
      '1 cda aceite oliva',
      'Ajo en polvo',
      'Pimentón',
      'Orégano',
      'Sal, pimienta',
    ],
    steps: [
      'Cocer arroz integral 18-20 min en agua hirviendo con sal. Escurrir.',
      'Sazonar pechuga con ajo, pimentón, orégano, sal y pimienta. Dejar 5 min.',
      'Calentar sartén con aceite. Cocinar pechuga 6 min por lado a fuego medio-alto.',
      'Cocinar brócoli al vapor 5 min. Filetear pollo en diagonal. Servir con arroz y brócoli.',
    ],
  },
  {
    id: 9,
    name: 'Batido Proteico',
    emoji: '🥛',
    cat: 'proteina',
    level: 'principiante',
    time: 5,
    kcal: 450,
    servings: 1,
    prot: 45,
    carb: 42,
    fat: 10,
    desc: 'Batido de proteína de suero con leche, plátano, mantequilla de maní y avena. Post-entreno de alta densidad nutricional.',
    ingredients: [
      '1 scoop proteína whey chocolate',
      '300ml leche entera o vegetal',
      '1 plátano maduro',
      '2 cdas mantequilla maní',
      '30g avena',
      'Hielo',
    ],
    steps: [
      'Pesar todos los ingredientes con exactitud para control de macros.',
      'Colocar en licuadora: leche, proteína, plátano, mantequilla de maní y avena.',
      'Licuar 30 segundos a velocidad máxima. Agregar hielo y pulsar 10 seg más.',
      'Verter inmediatamente. Consumir dentro de los 30 min post-entreno para máxima absorción.',
    ],
  },
  {
    id: 10,
    name: 'Quinoa con Pollo y Verduras',
    emoji: '🥙',
    cat: 'proteina',
    level: 'intermedio',
    time: 35,
    kcal: 580,
    servings: 2,
    prot: 48,
    carb: 55,
    fat: 14,
    desc: 'Quinoa cocida con tiras de pollo marinado, pimiento, zanahoria y salsa teriyaki reducida.',
    ingredients: [
      '150g quinoa',
      '300g pechuga pollo',
      '1 pimiento rojo',
      '2 zanahorias',
      '3 cdas salsa soja',
      '1 cda miel',
      'Jengibre',
      'Ajo',
      'Aceite sésamo',
    ],
    steps: [
      'Marinar pollo en tiras con soja, miel, ajo y jengibre 15 min.',
      'Cocer quinoa 15 min. Saltear pimiento y zanahoria juliana en aceite sésamo 4 min.',
      'Añadir pollo marinado al wok. Saltear a fuego alto 5-6 min hasta dorado.',
      'Mezclar quinoa con verduras y pollo. Reducir marinada 2 min y glasear. Sésamo encima.',
    ],
  },
  {
    id: 11,
    name: 'Ensalada Griega',
    emoji: '🥙',
    cat: 'mediterraneo',
    level: 'principiante',
    time: 10,
    kcal: 320,
    servings: 2,
    prot: 10,
    carb: 18,
    fat: 24,
    desc: 'Tomate, pepino, cebolla morada, aceitunas Kalamata, queso feta y orégano con aceite de oliva virgen extra.',
    ingredients: [
      '3 tomates maduros',
      '1 pepino',
      '1/2 cebolla morada',
      '100g feta',
      '80g aceitunas Kalamata',
      'Aceite oliva virgen extra',
      'Orégano seco',
      'Sal marina',
    ],
    steps: [
      'Cortar tomates y pepino en trozos irregulares grandes. No picar demasiado fino.',
      'Laminar cebolla morada y remojar 5 min en agua fría para suavizar el sabor.',
      'Disponer verduras en fuente. Colocar feta entero encima (no desmenuzar antes).',
      'Agregar aceitunas. Regar generosamente con aceite oliva. Orégano y sal marina al gusto.',
    ],
  },
  {
    id: 12,
    name: 'Pasta Integral Primavera',
    emoji: '🍝',
    cat: 'mediterraneo',
    level: 'intermedio',
    time: 30,
    kcal: 460,
    servings: 2,
    prot: 16,
    carb: 72,
    fat: 14,
    desc: 'Pasta integral con verduras de temporada, albahaca fresca, tomates cherry y pecorino.',
    ingredients: [
      '200g pasta integral',
      'Cherry 200g',
      '1 calabacín',
      '1 pimiento amarillo',
      'Albahaca fresca',
      '40g pecorino',
      '3 dientes ajo',
      'Aceite oliva',
      'Sal, pimienta',
    ],
    steps: [
      'Cocer pasta al dente según paquete. Reservar 1 taza del agua de cocción.',
      'Saltear ajo en aceite caliente. Añadir pimiento y calabacín. Cocinar 5 min.',
      'Agregar cherry cortados por la mitad. Saltear 2 min. Añadir pasta y agua reservada.',
      'Mezclar a fuego bajo. Añadir albahaca rasgada y pecorino. Ajustar sal y pimienta.',
    ],
  },
  {
    id: 13,
    name: 'Hummus Casero',
    emoji: '🫘',
    cat: 'mediterraneo',
    level: 'principiante',
    time: 10,
    kcal: 180,
    servings: 6,
    prot: 8,
    carb: 22,
    fat: 8,
    desc: 'Hummus suave de garbanzos con tahini, limón, ajo y aceite de oliva.',
    ingredients: [
      '400g garbanzos cocidos',
      '3 cdas tahini',
      '2 limones (zumo)',
      '2 dientes ajo',
      '3 cdas aceite oliva',
      'Sal',
      'Agua fría 3 cdas',
      'Pimentón y perejil para decorar',
    ],
    steps: [
      'Escurrir garbanzos. Reservar 2 cdas para decorar. Pelar los garbanzos para textura más suave.',
      'Procesar ajo, tahini y limón en procesadora hasta cremoso, 1 min.',
      'Añadir garbanzos progresivamente. Agregar agua fría y aceite mientras procesa.',
      'Rectificar sal y limón. Servir en plato hondo con aceite, pimentón y perejil.',
    ],
  },
  {
    id: 14,
    name: 'Lubina al Horno con Olivas',
    emoji: '🐟',
    cat: 'mediterraneo',
    level: 'avanzado',
    time: 50,
    kcal: 420,
    servings: 4,
    prot: 38,
    carb: 8,
    fat: 26,
    desc: 'Lubina entera al horno con olivas, tomates cherry, vino blanco, alcaparras y hierbas provenzales.',
    ingredients: [
      '1 lubina 1.2kg',
      '200g cherry',
      '100g olivas verdes',
      '100ml vino blanco seco',
      '2 cdas alcaparras',
      'Hierbas provenzales',
      'Ajo laminado',
      'Aceite oliva',
      'Limón',
    ],
    steps: [
      'Precalentar horno a 200°C. Limpiar lubina, hacer cortes en el lomo y rellenar con ajo y limón.',
      'Disponer cherry y olivas en fuente. Colocar lubina encima. Salpimentar generosamente.',
      'Verter vino blanco y aceite. Espolvorear hierbas y alcaparras. Láminas de limón encima.',
      'Hornear 30-35 min hasta que la piel esté crujiente. Reposar 5 min antes de servir.',
    ],
  },
  {
    id: 15,
    name: 'Ensalada Tropical Paleo',
    emoji: '🥗',
    cat: 'paleo',
    level: 'principiante',
    time: 20,
    kcal: 380,
    servings: 2,
    prot: 32,
    carb: 28,
    fat: 16,
    desc: 'Pechuga de pollo grillada con mango, aguacate, coco rallado y aderezo de lima.',
    ingredients: [
      '300g pechuga pollo',
      '1 mango maduro',
      '1 aguacate',
      'Mix de hojas verdes',
      'Coco rallado sin azúcar',
      'Zumo 2 limas',
      'Aceite de coco',
      'Sal, pimienta',
    ],
    steps: [
      'Sazonar pechuga con sal, pimienta y coco rallado. Grillar 6 min por lado.',
      'Cortar mango y aguacate en cubos. Preparar aderezo con lima y aceite de coco.',
      'Reposar pollo 3 min y cortar en láminas diagonales.',
      'Montar: hojas verdes, mango, aguacate, pollo. Aderezo y coco tostado encima.',
    ],
  },
  {
    id: 16,
    name: 'Costillas BBQ Paleo',
    emoji: '🍖',
    cat: 'paleo',
    level: 'avanzado',
    time: 180,
    kcal: 680,
    servings: 4,
    prot: 48,
    carb: 12,
    fat: 48,
    desc: 'Costillas de cerdo con marinada paleo de miel de agave, mostaza, ajo y hierbas. Horneadas lentamente.',
    ingredients: [
      '1.5kg costillas cerdo',
      '3 cdas miel agave',
      '2 cdas mostaza Dijon',
      '4 dientes ajo',
      'Romero fresco',
      'Tomillo',
      'Pimentón ahumado',
      'Sal marina gruesa',
      'Pimienta negra',
    ],
    steps: [
      'Retirar membrana de costillas. Mezclar marinada: miel, mostaza, ajo, especias y hierbas.',
      'Cubrir costillas con marinada y refrigerar mínimo 2 horas (idealmente toda la noche).',
      'Envolver en papel aluminio y hornear a 150°C por 2.5 horas. Retirar papel los últimos 30 min.',
      'Opcional: terminar 3 min en grill para caramelizar. Reposar 5 min antes de cortar.',
    ],
  },
  {
    id: 17,
    name: 'Huevos con Verduras Paleo',
    emoji: '🍳',
    cat: 'paleo',
    level: 'principiante',
    time: 15,
    kcal: 310,
    servings: 1,
    prot: 20,
    carb: 18,
    fat: 20,
    desc: 'Huevos fritos en aceite de coco con pimiento, champiñones, espinacas y boniato troceado.',
    ingredients: [
      '3 huevos',
      '100g boniato',
      '1/2 pimiento rojo',
      '80g champiñones',
      '40g espinacas',
      '1 cda aceite coco',
      'Sal',
      'Pimienta',
      'Pimentón dulce',
    ],
    steps: [
      'Cortar boniato en cubitos pequeños y saltear en aceite de coco 5 min hasta dorar.',
      'Añadir pimiento y champiñones laminados. Saltear 3 min más a fuego medio.',
      'Incorporar espinacas, remover hasta marchitar. Crear huecos y casacr los huevos.',
      'Tapar sartén 2 min para cocer claras manteniendo yemas líquidas. Salpimentar.',
    ],
  },
  {
    id: 18,
    name: 'Tortilla Española S/G',
    emoji: '🥚',
    cat: 'singluten',
    level: 'intermedio',
    time: 35,
    kcal: 360,
    servings: 4,
    prot: 16,
    carb: 28,
    fat: 22,
    desc: 'Tortilla de patatas y cebolla caramelizada, 100% sin gluten. Jugosa por dentro y dorada por fuera.',
    ingredients: [
      '600g patatas',
      '6 huevos',
      '1 cebolla grande',
      '150ml aceite oliva',
      'Sal',
      'Perejil opcional',
    ],
    steps: [
      'Pelar y laminar patatas finas. Pochar en aceite a 130°C con cebolla 20 min sin dorar.',
      'Escurrir aceite. Batir huevos con sal. Mezclar con patatas y cebolla. Reposar 5 min.',
      'En sartén antiadherente con poco aceite, verter mezcla a fuego medio. Cuajar bordes.',
      'Dar vuelta con plato. Deslizar de nuevo a sartén 3 min. Debe quedar jugosa al centro.',
    ],
  },
  {
    id: 19,
    name: 'Arroz con Mariscos S/G',
    emoji: '🦐',
    cat: 'singluten',
    level: 'avanzado',
    time: 50,
    kcal: 520,
    servings: 4,
    prot: 32,
    carb: 64,
    fat: 12,
    desc: 'Arroz bomba con gambas, mejillones, calamar y caldo de pescado casero. Receta 100% libre de gluten.',
    ingredients: [
      '320g arroz bomba',
      '300g gambas',
      '400g mejillones',
      '200g calamar',
      '1L caldo pescado casero',
      '1 cebolla',
      'Azafrán',
      'Pimentón',
      'Ajo',
      'Tomate frito',
    ],
    steps: [
      'Sofreír cebolla y ajo en paellera. Añadir tomate y pimentón. Cocinar 5 min.',
      'Agregar calamar troceado, saltear 2 min. Incorporar arroz y sofreír 1 min.',
      'Verter caldo caliente con azafrán infusionado. Fuego alto 5 min, medio 12 min, sin remover.',
      'Añadir gambas y mejillones los últimos 5 min. Reposar 5 min tapado con paño.',
    ],
  },
  {
    id: 20,
    name: 'Ceviche de Camarón',
    emoji: '🍋',
    cat: 'singluten',
    level: 'intermedio',
    time: 20,
    kcal: 280,
    servings: 3,
    prot: 26,
    carb: 18,
    fat: 8,
    desc: 'Camarones marinados en jugo de limón con cebolla morada, cilantro, tomate y ají.',
    ingredients: [
      '500g camarones crudos pelados',
      '6 limones (zumo)',
      '1 cebolla morada',
      '2 tomates',
      '1 ají amarillo',
      'Cilantro fresco',
      'Sal',
      'Pimienta',
      'Tostadas sin gluten',
    ],
    steps: [
      'Limpiar camarones y cortar en mitades. Marinar en zumo de limón 10 min en nevera.',
      'Cortar cebolla morada en juliana fina. Remojar en agua fría 5 min para suavizar.',
      'Picar tomate en cubitos, cilantro y ají (sin semillas para menos picante).',
      'Escurrir un poco el limón. Mezclar todo. Rectificar sal. Servir frío con tostadas.',
    ],
  },
  {
    id: 21,
    name: 'Bowl de Atún Keto S/G',
    emoji: '🥑',
    cat: 'keto singluten',
    level: 'principiante',
    time: 10,
    kcal: 390,
    servings: 1,
    prot: 34,
    carb: 6,
    fat: 26,
    desc: 'Atún en aceite con aguacate en cubos, pepino, sésamo tostado y aderezo de ponzu.',
    ingredients: [
      '1 lata atún en aceite',
      '1 aguacate',
      '1/2 pepino',
      '1 cda salsa ponzu',
      '1 cdita aceite sésamo',
      'Sésamo tostado',
      'Cebollín',
      'Rábano (opcional)',
    ],
    steps: [
      'Escurrir atún conservando un poco de aceite para sabor. Desmenuzar en bowl.',
      'Cortar aguacate y pepino en cubos uniformes de 1cm.',
      'Preparar aderezo: ponzu + aceite de sésamo + cebollín picado.',
      'Montar bowl: base de lechuga, atún, aguacate y pepino. Regar aderezo y sésamo encima.',
    ],
  },
];

export const RECIPE_CARDS: RecipeCard[] = [
  { id: 1, cat: 'vegano', level: 'principiante', accent: 'linear-gradient(135deg,#43a047,#66bb6a)', levelLabel: 'Fácil', icon: '🥗', title: 'Buddha Bowl de Quinoa', desc: 'Bowl nutritivo con quinoa, garbanzos crujientes, aguacate, espinacas y aderezo tahini. Rico en proteína vegetal y fibra.', time: '25 min', kcal: '420 kcal', servings: '2 pers.' },
  { id: 2, cat: 'vegano', level: 'intermedio', accent: 'linear-gradient(135deg,#ff8f00,#ffca28)', levelLabel: 'Medio', icon: '🍛', title: 'Curry de Garbanzos', desc: 'Curry cremoso con leche de coco, garbanzos, tomate, jengibre y especias aromáticas. Servir con arroz basmati.', time: '35 min', kcal: '380 kcal', servings: '4 pers.' },
  { id: 3, cat: 'vegano', level: 'intermedio', accent: 'linear-gradient(135deg,#00897b,#26c6da)', levelLabel: 'Medio', icon: '🌮', title: 'Tacos de Jackfruit BBQ', desc: 'Jackfruit desmenuzado con salsa BBQ ahumada, col morada encurtida y crema de cilantro. Alternativa vegana perfecta.', time: '40 min', kcal: '310 kcal', servings: '3 pers.' },
  { id: 4, cat: 'vegano', level: 'principiante', accent: 'linear-gradient(135deg,#29b6f6,#4fc3f7)', levelLabel: 'Fácil', icon: '🥤', title: 'Smoothie Verde Energizante', desc: 'Licuado de espinaca, mango, jengibre, leche de almendras y semillas de chía. Desayuno rápido y lleno de nutrientes.', time: '5 min', kcal: '220 kcal', servings: '1 pers.' },
  { id: 5, cat: 'keto', level: 'principiante', accent: 'linear-gradient(135deg,#e53935,#ef9a9a)', levelLabel: 'Fácil', icon: '🐟', title: 'Salmón con Aguacate', desc: 'Filete de salmón a la plancha con salsa de aguacate y limón, acompañado de espárragos salteados en mantequilla.', time: '20 min', kcal: '550 kcal', servings: '2 pers.' },
  { id: 6, cat: 'keto', level: 'principiante', accent: 'linear-gradient(135deg,#ffa000,#ffc107)', levelLabel: 'Fácil', icon: '🥚', title: 'Huevos con Bacon Keto', desc: 'Huevos revueltos cremosos con bacon crujiente, queso parmesano y cebollín. Desayuno alto en grasa y proteína.', time: '15 min', kcal: '420 kcal', servings: '1 pers.' },
  { id: 7, cat: 'keto', level: 'intermedio', accent: 'linear-gradient(135deg,#5e35b1,#9c27b0)', levelLabel: 'Medio', icon: '🍗', title: 'Pollo al Limón Keto', desc: 'Muslos de pollo a la sartén con salsa de mantequilla, limón y ajo, acompañados de coliflor gratinada con queso.', time: '30 min', kcal: '480 kcal', servings: '2 pers.' },
  { id: 8, cat: 'proteina', level: 'principiante', accent: 'linear-gradient(135deg,#1565c0,#42a5f5)', levelLabel: 'Fácil', icon: '🏋️', title: 'Pechuga con Arroz', desc: 'Pechuga de pollo a la plancha con condimento de hierbas, arroz integral y verduras al vapor. Clásico de ganancia muscular.', time: '20 min', kcal: '520 kcal', servings: '1 pers.' },
  { id: 9, cat: 'proteina', level: 'principiante', accent: 'linear-gradient(135deg,#6d4c41,#a1887f)', levelLabel: 'Fácil', icon: '🥛', title: 'Batido Proteico', desc: 'Batido de proteína de suero con leche, plátano, mantequilla de maní y avena. Post-entreno de alta densidad nutricional.', time: '5 min', kcal: '450 kcal', servings: '1 pers.' },
  { id: 10, cat: 'proteina', level: 'intermedio', accent: 'linear-gradient(135deg,#00695c,#4caf50)', levelLabel: 'Medio', icon: '🥙', title: 'Quinoa con Pollo y Verduras', desc: 'Quinoa cocida con tiras de pollo marinado, pimiento, zanahoria y salsa teriyaki reducida. Alta en proteína completa.', time: '35 min', kcal: '580 kcal', servings: '2 pers.' },
  { id: 11, cat: 'mediterraneo', level: 'principiante', accent: 'linear-gradient(135deg,#1976d2,#42a5f5)', levelLabel: 'Fácil', icon: '🥙', title: 'Ensalada Griega', desc: 'Tomate, pepino, cebolla morada, aceitunas Kalamata, queso feta y orégano con aceite de oliva virgen extra.', time: '10 min', kcal: '320 kcal', servings: '2 pers.' },
  { id: 12, cat: 'mediterraneo', level: 'intermedio', accent: 'linear-gradient(135deg,#e64a19,#ff8a65)', levelLabel: 'Medio', icon: '🍝', title: 'Pasta Integral Primavera', desc: 'Pasta integral con verduras de temporada, albahaca fresca, tomates cherry y pecorino. Ligera y equilibrada.', time: '30 min', kcal: '460 kcal', servings: '2 pers.' },
  { id: 13, cat: 'mediterraneo', level: 'principiante', accent: 'linear-gradient(135deg,#f9a825,#fdd835)', levelLabel: 'Fácil', icon: '🫘', title: 'Hummus Casero', desc: 'Hummus suave de garbanzos con tahini, limón, ajo y aceite de oliva. Decorado con pimentón ahumado y semillas.', time: '10 min', kcal: '180 kcal', servings: '6 pers.' },
  { id: 14, cat: 'mediterraneo', level: 'avanzado', accent: 'linear-gradient(135deg,#0288d1,#4fc3f7)', levelLabel: 'Avanzado', icon: '🐟', title: 'Lubina al Horno con Olivas', desc: 'Lubina entera al horno con olivas, tomates cherry, vino blanco, alcaparras y hierbas provenzales. Plato de gala.', time: '50 min', kcal: '420 kcal', servings: '4 pers.' },
  { id: 15, cat: 'paleo', level: 'principiante', accent: 'linear-gradient(135deg,#6d4c41,#ff7043)', levelLabel: 'Fácil', icon: '🥗', title: 'Ensalada Tropical de Pollo', desc: 'Pechuga de pollo grillada con mango, aguacate, coco rallado y aderezo de lima. Fresca y completamente paleo.', time: '20 min', kcal: '380 kcal', servings: '2 pers.' },
  { id: 16, cat: 'paleo', level: 'avanzado', accent: 'linear-gradient(135deg,#b71c1c,#e53935)', levelLabel: 'Avanzado', icon: '🍖', title: 'Costillas BBQ Paleo', desc: 'Costillas de cerdo con marinada paleo de miel de agave, mostaza, ajo y hierbas. Horneadas lentamente para máxima ternura.', time: '3 h', kcal: '680 kcal', servings: '4 pers.' },
  { id: 17, cat: 'paleo', level: 'principiante', accent: 'linear-gradient(135deg,#558b2f,#aed581)', levelLabel: 'Fácil', icon: '🍳', title: 'Huevos con Verduras Paleo', desc: 'Huevos fritos en aceite de coco con pimiento, champiñones, espinacas y boniato troceado. Desayuno completo y nutritivo.', time: '15 min', kcal: '310 kcal', servings: '1 pers.' },
  { id: 18, cat: 'singluten', level: 'intermedio', accent: 'linear-gradient(135deg,#f57f17,#ffca28)', levelLabel: 'Medio', icon: '🥚', title: 'Tortilla Española S/G', desc: 'Tortilla de patatas y cebolla caramelizada, 100% sin gluten. Jugosa por dentro y dorada por fuera. Tapas definitiva.', time: '35 min', kcal: '360 kcal', servings: '4 pers.' },
  { id: 19, cat: 'singluten', level: 'avanzado', accent: 'linear-gradient(135deg,#0277bd,#29b6f6)', levelLabel: 'Avanzado', icon: '🦐', title: 'Arroz con Mariscos S/G', desc: 'Arroz bomba con gambas, mejillones, calamar y caldo de pescado casero. Receta 100% libre de gluten.', time: '50 min', kcal: '520 kcal', servings: '4 pers.' },
  { id: 20, cat: 'singluten', level: 'intermedio', accent: 'linear-gradient(135deg,#00838f,#4dd0e1)', levelLabel: 'Medio', icon: '🍋', title: 'Ceviche de Camarón', desc: 'Camarones marinados en jugo de limón con cebolla morada, cilantro, tomate y ají. Fresco, saludable y sin gluten.', time: '20 min', kcal: '280 kcal', servings: '3 pers.' },
  { id: 21, cat: 'keto singluten', level: 'principiante', accent: 'linear-gradient(135deg,#4a148c,#7b1fa2)', levelLabel: 'Fácil', icon: '🥑', title: 'Bowl de Atún Keto S/G', desc: 'Atún en aceite con aguacate en cubos, pepino, sésamo tostado y aderezo de ponzu. Listo en 10 minutos.', time: '10 min', kcal: '390 kcal', servings: '1 pers.' },
];
